// Package vmpmobile exposes VMPacker's ARM64 ELF protection engine to Android
// through gomobile bind.
//
// The public API deliberately uses only gomobile-friendly types — string, bool,
// int, error, and a single Logger interface — so the generated Java/Kotlin
// binding stays small and stable. Structured data crosses the boundary as JSON
// strings, which avoids gomobile's struct/slice marshaling limitations.
//
// Build (produces an .aar consumed by the Android app):
//
//	gomobile bind -target=android/arm64,android/arm \
//	    -androidapi 24 -javapkg com.vmpacker.mobile \
//	    -o android/app/libs/vmpmobile.aar ./mobile
package vmpmobile

import (
	"bufio"
	"debug/elf"
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"

	elfpacker "github.com/vmpacker/pkg/binary/elf"
)

// interpBlob is the ARM64 VM interpreter blob. It is generated by compiling
// stub/linux/arm64/vm_interp.c (see the CI workflow) and must be present at
// build time; the file is git-ignored because it is a build artifact.
//
//go:embed vm_interp.bin
var interpBlob []byte

// Logger receives engine log lines. Implement it in Kotlin to stream progress
// into the UI. Its Log method is invoked from a background goroutine, so a
// Kotlin implementation must marshal UI updates back onto the main thread.
type Logger interface {
	Log(line string)
}

// engineMu serializes Protect runs: the engine writes progress to os.Stdout,
// which Protect temporarily redirects, so only one run may be active at a time.
var engineMu sync.Mutex

// BlobSize reports the embedded interpreter blob size in bytes. It is non-zero
// only when the .aar was built with a properly generated blob, so the UI can
// surface a clear error instead of failing deep inside the engine.
func BlobSize() int { return len(interpBlob) }

// funcEntry is the JSON shape exchanged with the UI for both Analyze output and
// Protect input.
type funcEntry struct {
	Name     string `json:"name"`
	Address  string `json:"address"` // hex, e.g. "0x4006AC"
	Size     int64  `json:"size"`
	IsCustom bool   `json:"isCustom"` // true => protect by [Addr, Addr+Size); else by symbol name
}

// Analyze opens an ARM64 ELF and returns a JSON document:
//
//	{"fileName":..,"arch":"ARM64","format":"ELF",
//	 "functions":[{"name":..,"address":"0x..","size":N}, ...]}
//
// It mirrors the desktop GUI's analysis: STT_FUNC symbols with non-zero size
// that fall inside .text, falling back to dynamic symbols for stripped files.
func Analyze(path string) (string, error) {
	f, err := elf.Open(path)
	if err != nil {
		return "", fmt.Errorf("打开 ELF 失败: %w", err)
	}
	defer f.Close()

	if f.Machine != elf.EM_AARCH64 {
		return "", fmt.Errorf("仅支持 ARM64 (AArch64) ELF")
	}

	syms, err := f.Symbols()
	if err != nil {
		if syms, err = f.DynamicSymbols(); err != nil {
			return "", fmt.Errorf("无法读取符号表或动态符号表（可能是被完全抹除符号的程序）: %w", err)
		}
	}

	text := f.Section(".text")
	funcs := make([]funcEntry, 0, len(syms))
	for _, s := range syms {
		if elf.ST_TYPE(s.Info) != elf.STT_FUNC || s.Size == 0 {
			continue
		}
		if text != nil && (s.Value < text.Addr || s.Value >= text.Addr+text.Size) {
			continue
		}
		funcs = append(funcs, funcEntry{
			Name:    s.Name,
			Address: fmt.Sprintf("0x%X", s.Value),
			Size:    int64(s.Size),
		})
	}

	out := map[string]interface{}{
		"fileName":  filepath.Base(path),
		"arch":      "ARM64",
		"format":    "ELF",
		"functions": funcs,
	}
	b, err := json.Marshal(out)
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// Protect runs the VMP engine on inputPath and writes the protected ELF to
// outputPath (defaulting to inputPath+".vmp" when empty). funcsJSON is a JSON
// array of funcEntry objects: entries with isCustom=true are protected by
// address range, the rest by symbol name. The returned string is the output
// path. Engine progress is streamed to logger line by line.
func Protect(inputPath, outputPath, funcsJSON string, stripSymbols, debug, tokenEntry bool, logger Logger) (string, error) {
	engineMu.Lock()
	defer engineMu.Unlock()

	if len(interpBlob) == 0 {
		return "", fmt.Errorf("内置解释器 blob 为空：.aar 未随生成的 vm_interp.bin 一起构建")
	}
	if outputPath == "" {
		outputPath = inputPath + ".vmp"
	}

	var entries []funcEntry
	if strings.TrimSpace(funcsJSON) != "" {
		if err := json.Unmarshal([]byte(funcsJSON), &entries); err != nil {
			return "", fmt.Errorf("函数列表 JSON 解析失败: %w", err)
		}
	}

	var names []string
	var specs []elfpacker.AddrSpec
	for _, e := range entries {
		if e.IsCustom {
			addr, err := parseHexAddr(e.Address)
			if err != nil {
				emit(logger, fmt.Sprintf("[!] 跳过地址解析失败的项 %q: %v", e.Address, err))
				continue
			}
			specs = append(specs, elfpacker.AddrSpec{Addr: addr, End: addr + uint64(e.Size), Name: e.Name})
		} else if strings.TrimSpace(e.Name) != "" {
			names = append(names, e.Name)
		}
	}
	if len(names) == 0 && len(specs) == 0 {
		return "", fmt.Errorf("未选择任何要保护的函数")
	}

	// Stream the engine's os.Stdout output to the UI logger for the duration of
	// Process(). engineMu guarantees no concurrent redirect.
	restore := redirectStdout(logger)
	defer restore()

	packer := elfpacker.NewPacker(inputPath, outputPath, names, specs, true, stripSymbols, debug, tokenEntry, interpBlob)
	if err := packer.Process(); err != nil {
		return "", err
	}
	return outputPath, nil
}

func emit(l Logger, s string) {
	if l != nil {
		l.Log(s)
	}
}

// parseHexAddr parses "0x....", "0X...." or a bare hex string into a uint64.
func parseHexAddr(s string) (uint64, error) {
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "0x")
	s = strings.TrimPrefix(s, "0X")
	return strconv.ParseUint(s, 16, 64)
}

// redirectStdout pipes os.Stdout to the logger line by line until the returned
// function is called, which restores the original stdout and drains the reader.
func redirectStdout(l Logger) func() {
	if l == nil {
		return func() {}
	}
	orig := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		return func() {}
	}
	os.Stdout = w

	done := make(chan struct{})
	go func() {
		sc := bufio.NewScanner(r)
		sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
		for sc.Scan() {
			l.Log(sc.Text())
		}
		close(done)
	}()

	return func() {
		_ = w.Close()
		os.Stdout = orig
		<-done
		_ = r.Close()
	}
}
